#!/bin/sh
#

# PROVIDE: jmaker_server
# REQUIRE: NETWORKING

. /etc/rc.subr

export PATH="$PATH:/usr/local/bin"
_programm="jmaker-server"
_procname="/usr/local/bin/${_programm}"

name="jmaker_server"
rcvar=${name}_enable

load_rc_config $name

pidfile="/var/run/${_programm}"
procname="/usr/local/bin/node"
command="/usr/sbin/daemon"

: ${jmaker_server_enable="NO"}
: ${jmaker_server_config="/usr/local/etc/${_programm}.yml"}

command_args="-f -t ${_programm} -p ${pidfile} ${_procname} --config=${jmaker_server_config}"

run_rc_command "$1"
